# Server configuration parameters
main_gpu: 1
n_gpu_layers: 99
split_mode: LLAMA_SPLIT_MODE_ROW  # how to split the model across GPUs
tensor_split: [0]  # how split tensors should be distributed across GPUs
use_mmap: true     # use mmap for faster loads
use_mlock: false   # use mlock to keep model in memory
check_tensors: false  # validate tensor data
n_threads: 64      # number of threads to use for computation
n_threads_batch: 64 # number of threads to use for batch processing
defrag_thold: 0.5   # defragmentation threshold
no_perf: false      # disable performance metrics
enable_mla: true        # use mla for deepseek
enable_fused_moe: true  # use fused moe for deepseek

# Generation parameters
n_ctx: 65536  # context size (1024 * 16 * 16)
n_batch: 512  # logical batch size for prompt processing
n_parallel: 16  # number of parallel sequences to decode (must < 32 now)

# Model parameters
model: "/root/data/DeepSeek-V2-Lite-Chat-f16.gguf"  # model path
model_alias: ""  # model alias

# Server parameters
special: false       # enable special token output
cont_batching: true  # insert new sequences for decoding on-the-fly
reranking: false     # enable reranking support on server
port: 8080           # server listens on this network port
n_threads_http: -1   # number of threads to process HTTP requests
hostname: "127.0.0.1"  # server hostname
chat_template: ""    # chat template

# Reasoning format
reasoning_format: COMMON_REASONING_FORMAT_DEEPSEEK
